# Generated by Django 3.1.1 on 2020-09-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200908_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='P'),
            preserve_default=False,
        ),
    ]
